/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 megaphone.glb 
Author: Toxic_Aura (https://sketchfab.com/toxicaura_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/megaphone-737126c497f048e388935ffad2355f35
Title: Megaphone
*/

import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Megaphone(props) {
  const { nodes, materials } = useGLTF('/megaphone.glb')
  return (
    <group {...props} dispose={null}>
      {/* <group name="camera" position={[10, 0, 50]} rotation={[Math.PI / 2, 0, 0]}>
        <PerspectiveCamera fov={40} near={10} far={1000} />
      </group> */}
      {/* <group name="sun" position={[100, 50, 100]} rotation={[-Math.PI / 2, 0, 0]}>
        <pointLight intensity={10} />
      </group> */}
      <mesh
        geometry={nodes.Megaphone_Megaphone_Mat_0.geometry}
        material={materials.Megaphone_Mat}
        scale={20}
        castShadow
      />
    </group>
  )
}

useGLTF.preload('/megaphone.glb')
